# Generated by Django 3.2.5 on 2021-07-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userprofile',
        ),
    ]
