# Generated by Django 3.1 on 2021-08-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210829_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
